//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica5_2DesarrolloWebUASD.Models.ModelDB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    public partial class Registro
    {

        [Key]
        public int RegistroID { get; set; }
        [Range(16000, 100000, ErrorMessage = "El sueldo minimo es de 16000 pesos")]
        [Required(ErrorMessage = "El campo es obligatorio.")]
        public Nullable<decimal> Sueldo { get; set; }


        [Display(Name = "Clave departamento")]
        public int DepartemantoID { get; set; }

    
        [Display(Name = "Empleado")]
        public int EmpleadoID { get; set; }

        [Display(Name ="Departamento")]
        public Nullable<int> Departamento_DepartamentoID { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
